/* eslint-disable */
// Auto-generated by npm run swatches. Do not edit by hand.
export const TONE_SWATCH_HEX = {
  "light": {
    "cream": "#94482e",
    "powder": "#9a856f"
  },
  "bronzer": {
    "cream": "#98461f",
    "powder": "#998170"
  },
  "deep": {
    "cream": "#952617",
    "powder": "#936e5e"
  }
} as const;
