// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema:
    process.env["PRISMA_PROVIDER"] === "sqlite"
      ? "prisma/schema.sqlite.prisma"
      : "prisma/schema.postgres.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // Vercel Postgres / Neon integrations often provide POSTGRES_* vars even when DATABASE_URL
    // wasn't added manually. Prefer DATABASE_URL, then fall back to common Vercel keys.
    url:
      process.env["DATABASE_URL"] ??
      process.env["POSTGRES_PRISMA_URL"] ??
      process.env["POSTGRES_URL_NON_POOLING"] ??
      process.env["POSTGRES_URL"],
  },
});
